# Processes a sample mutual inductance measurement end-to-end:
#   1. Applies the phase/leakage corrections from the calibration run
#   2. Normalises MI to the normal-state value
#   3. Converts normalised MI → London penetration depth λ(T) via a pre-computed lookup table
# Run process_calibration_data.py and calc_MI_lookup_table.py first.

import os
import sys
# The line below makes this script runnable from any working directory without installing the package.
# In your own analysis code, add the repo root to your PYTHONPATH instead
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import numpy as np
from mutual_inductance.mutual_inductance_data import MIData

here = os.path.dirname(os.path.abspath(__file__))

name      = 'sample_data_example'
data_name = os.path.join(here, 'example_data', f'{name}.dat')

# columns: T (K), X (V), Y (V)  — X/Y are the in-phase and quadrature lock-in outputs
dat = np.loadtxt(data_name, skiprows=1)
T = dat[:,0]
X = dat[:,1]
Y = dat[:,2]

f = 6e4       # lock-in reference frequency (Hz)
V = 3         # drive voltage (V)
R = 9.93e3    # series resistance (Ω) — sets the drive current
I = V/R

# corrections extracted from the calibration run (process_calibration_data.py);
# the exact values are printed to stdout and saved in the header of the calibration output file
leakage = 9.66893011248539e-10   # field leakage offset in MI_x (H)
angle   = 1.603212699619901      # phase mixing angle between X and Y channels (rad)

# lookup table mapping λ → MI/MI_∞, generated by calc_MI_lookup_table.py
lookup_table_path = os.path.join(here, 'lookup_table_7.0nm_calibration_data_example_calib.dat')

save_name = os.path.join(here, f'{name}_processed.dat')

MI = MIData(X, Y, T, f, I, leakage=leakage, correction_angle=angle, residual_capacitance=0)
# Tmin sets the lower bound for the normal-state average used to normalise MI;
# choose a temperature well above Tc so the film is fully in the normal state
MI.process_data(Tmin=11, save_name=save_name, n=100)
MI.convert_MI_to_PD(lookup_table_path, save_path=save_name)
